### ISSUE TITLE
已经安装上了但是好像不起作用

### ISSUE THREAD

**Issue by hong-tm** [cqjjjzr/MusicBee-NeteaseLyrics#11]
![Snipaste_2021-12-20_20-07-53](https://user-images.githubusercontent.com/51999870/146765129-3d6bd91e-54f0-4c94-bd87-d60e204877ce.png)
![Snipaste_2021-12-20_20-08-54](https://user-images.githubusercontent.com/51999870/146765184-9d18dd3e-a5ac-4864-82c5-67023146dcfc.png)

**Comment by cqjjjzr** [comment]
在 “正在播放”页面中看看？

**Comment by hong-tm** [comment]
![Snipaste_2021-12-20_20-13-52](https://user-images.githubusercontent.com/51999870/146765672-d2788f71-ec50-47cd-83e2-ab3bd1cfa418.png)
开了歌词但是没看到

**Comment by hong-tm** [comment]
之前后面的图片和歌手介绍都有

**Comment by hong-tm** [comment]
![Snipaste_2021-12-20_20-15-44](https://user-images.githubusercontent.com/51999870/146765855-853d9c2b-5c35-43e5-acfc-6da6c9029171.png)
之前那个应该是歌手问题这个有

**Comment by cqjjjzr** [comment]
尝试右键歌词区，删除歌词并重新查找，如果还没有就要考虑用设置 custom10 的方式了
这个界面有多种显示模式，需要切到歌词模式

**Comment by hong-tm** [comment]
> 尝试右键歌词区，删除歌词并重新查找，如果还没有就要考虑用设置 custom10 的方式了 这个界面有多种显示模式，需要切到歌词模式

尝试了重新查找，没看到删除歌词选项，依然没有歌词

**Comment by hong-tm** [comment]
![Snipaste_2021-12-20_20-19-35](https://user-images.githubusercontent.com/51999870/146766283-1df7e666-fab1-4c9c-ba13-79152d40bf8e.png)

**Comment by hong-tm** [comment]
> 尝试右键歌词区，删除歌词并重新查找，如果还没有就要考虑用设置 custom10 的方式了 这个界面有多种显示模式，需要切到歌词模式

custom 10 怎么操作

**Comment by cqjjjzr** [comment]
那就是网络问题（你在国内网络吗？）或没找到了，考虑用设置 Custom10 标签的方案

但这首歌我是可以不用 Custom10 找到的

**Comment by hong-tm** [comment]
> 那就是网络问题（你在国内网络吗？）或没找到了，考虑用设置 Custom10 标签的方案
> 
> 但这首歌我是可以不用 Custom10 找到的

我在马来西亚，foobar2k的es-lyric可以搜到
![Snipaste_2021-12-20_20-22-45](https://user-images.githubusercontent.com/51999870/146766719-9b7b01ee-95fc-40af-8191-5c07eee452d4.png)
![Snipaste_2021-12-20_20-22-58](https://user-images.githubusercontent.com/51999870/146766743-04a8b030-5178-4e50-9adb-6b0795012f71.png)

**Comment by cqjjjzr** [comment]
![image](https://user-images.githubusercontent.com/6622592/146766536-fd48bb3d-870c-440d-be45-c136ebd51955.png)
![image](https://user-images.githubusercontent.com/6622592/146766775-7e0b0047-a59e-46c6-a3d7-33081ca9e22a.png)

**Comment by cqjjjzr** [comment]
尝试访问 http://music.163.com/api/search/get/web?csrf_token=hlpretag=&hlposttag=&s=%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AB%E5%87%BA%E4%BC%9A%E3%82%8F%E3%81%AA%E3%81%91%E3%82%8C%E3%81%B0%20%EF%BD%9E%E5%A4%8F%E9%9B%AA%E5%86%AC%E8%8A%B1%EF%BD%9E&type=1&offset=0&total=true&limit=6

http://music.163.com/api/song/lyric?os=pc&id=476081896&lv=-1&kv=-1&tv=-1

这两个接口，看看结果如何

**Comment by hong-tm** [comment]
## 第一个好像不行，第二个有
{"sgc":false,"sfy":false,"qfy":false,"transUser":{"id":4134105,"status":99,"demand":1,"userid":59957287,"nickname":"虎纹鲨鱼子","uptime":1494406187549},"lyricUser":{"id":4134100,"status":99,"demand":0,"userid":59957287,"nickname":"虎纹鲨鱼子","uptime":1494406187549},"lrc":{"version":6,"lyric":"[00:00.000] 作词 : aimerrhythm\n[00:01.000] 作曲 : 百田留衣\n[00:15.520]記憶などいらない 永遠に眠りたい\n[00:28.570]もう このまま朝が 来なくたっていいや\n[00:39.930]\n[00:41.770]いつも夢の中では あなたは笑ってる\n[00:52.660]どうして ねえ 消えないの?\n[01:00.240]\n[01:00.880]I gave you everything.\n[01:02.390]You gave me anything?\n[01:04.000]きっと いつまででも\n[01:07.550]You're everything, still my everything.\n[01:10.670]愛してるんだよ\n[01:13.940]真夏に降った雪のような\n[01:20.500]それは儚い奇跡なんだ\n[01:26.230]\n[01:27.900]あなたに出会わなければ こんなに切なくて\n[01:36.650]胸を締め付けることもなかった…それでも\n[01:44.210]あなたに出会えなければ\n[01:49.900]強さも優しさも 知らないまま\n[01:56.690]部屋の隅で泣いていた 何も見えずに\n[02:06.420]\n[02:20.340]季節などいらない なにも触れたくない\n[02:33.440]もう あの花の名は 忘れたっていいや\n[02:45.000]\n[02:46.570]だけど夢の中では あなたは笑ってる\n[02:57.870]いまでも そうなんだ\n[03:05.320]\n[03:05.770]I gave you everything.\n[03:07.310]You gave me anything?\n[03:08.880]ずっと いつまででも\n[03:12.370]You're everything I'm still waiting.\n[03:15.570]愛しててもいい\n[03:18.990]真冬に咲いた 花のような\n[03:25.530]いまは儚い記憶でも\n[03:31.190]\n[03:32.610]あなたに出会わなければ こんなに寂しくて\n[03:41.650]涙が止まらない夜はなかった…それでも\n[03:49.090]あなたに贈りたい\n[03:53.590]ただ、「愛されていてね…」と\n[03:58.080]包まれてた はじめて笑えた夜の\n[04:06.960]わたしのように\n[04:10.980]\n[04:11.790]もしも願いがひとつ 叶うのなら\n[04:18.170]もう一度触れてほしい\n[04:25.010]生まれて良かったと感じれた\n[04:31.030]あの朝日に照らされて\n[04:41.090]\n[04:45.060]あなたに出会わなければ こんなに切なくて\n[04:54.110]胸を締め付けることもなかった…それでも\n[05:01.650]あなたに出会えなければ\n[05:07.260]強さも優しさも 知らずにいた\n[05:14.140]目を閉じれば すぐそこに あなたがいる\n[05:23.580]いまでも まだ 目を閉じれば\n[05:29.380]すぐそこに あなたがいる\n"},"klyric":{"version":0,"lyric":""},"tlyric":{"version":5,"lyric":"[by:虎纹鲨鱼子]\n[00:15.520]已不需要记忆 想要永远长眠\n[00:28.570]这样的话 早晨就无需到来\n[00:41.770]梦中的你 总是微笑着\n[00:52.660]呐 又为什么 挥散不去呢\n[01:00.880]I gave you everything.\n[01:02.390]You gave me anything?\n[01:04.000]一定是永恒的 但是\n[01:07.550]You're everything, still my everything.\n[01:10.670]我依然爱着你\n[01:13.940]就算是像盛夏落雪一样的\n[01:20.500]这样梦幻的奇迹(也没关系啊)\n[01:27.900]如果没有与你相遇 就无法懂得这伤感\n[01:36.650]即使如此 此刻 痛也揪心\n[01:44.210]如果没有与你相遇\n[01:49.900]便无法感受这温柔\n[01:56.690]我只能在房间的角落里哭泣 什么也看不见\n[02:20.340]已不需要季节 想要远离一切\n[02:33.440]我已忘记 那朵花儿的名字\n[02:46.570]但在梦中 你仍然微笑\n[02:57.870]又为什么 现在亦如此\n[03:05.770]I gave you everything.\n[03:07.310]You gave me anything?\n[03:08.880]一直 永远如此\n[03:12.370]You’re everything I’m still waiting.\n[03:15.570]我依然可以爱着你\n[03:18.990]就像是严冬花儿一样的\n[03:25.530]这样短暂的记忆 (即使如此 也没关系啊）\n[03:32.610]如果没有与你相遇 就无法体会这寂寞\n[03:41.650]即使如此 此夜 泪也不止\n[03:49.090]而你想要赠与我的\n[03:53.590]只是“被爱着”\n[03:58.080]被你第一次微笑的夜晚笼罩了\n[04:06.960]如同我一般\n[04:11.790]如果没有一个愿望能够实现\n[04:18.170]希望再次被你触碰\n[04:25.010]能够在此世界存在真是太好了\n[04:31.030]沐浴着朝阳...\n[04:45.060]如果没有与你相遇 就无法懂得这伤感\n[04:54.110]即使如此 此刻 痛也揪心\n[05:01.650]如果没有与你相遇\n[05:07.260]便无法感受这温柔\n[05:14.140]只要闭上眼 就能看见 你存于我身旁\n[05:23.580]即使是现在 只要闭上眼\n[05:29.380]依然能看见 你存于在我身旁\n"},"code":200}

**Comment by cqjjjzr** [comment]
那就是第一个搜索用的接口在国外没法用，可能 Foobar 上那个插件用了别的接口。

考虑要么用回国的梯子，要么用 Custom10 法，具体参照 README.md 里的教程。

**Comment by hong-tm** [comment]
## 这样子吗？

![Snipaste_2021-12-20_20-30-19](https://user-images.githubusercontent.com/51999870/146767543-88e41b29-cef3-4c9c-8844-35ad0efea708.png)

**Comment by cqjjjzr** [comment]
# 不是

是你需要手动在网易云上搜索每首歌，找到对应的 ID 并埴到歌曲的 Custom10 标签

先右键歌曲选编辑

![image](https://user-images.githubusercontent.com/6622592/146767877-0de7f4fc-3888-41a0-974b-a0d75266670d.png)

**Comment by hong-tm** [comment]
> # 不是
> 是你需要手动在网易云上搜索每首歌，找到对应的 ID 并埴到歌曲的 Custom10 标签
> 
> 先右键歌曲选编辑
> 
> ![image](https://user-images.githubusercontent.com/6622592/146767877-0de7f4fc-3888-41a0-974b-a0d75266670d.png)

感谢懂了

下面es用的


// Created by Elia <elia.of.little@gmail.com>
// Update 2016-08-09 19:36
// Require:
// - foobar2000 v1.3.3+ with ESLyric v0.3.5+
// Thanks: 
// - Moon for netease's api >>> [http://moonlib.com/606.html]
// - ttsping for ESLyric and sample scripts
// - keperlia, ABC超人1, etc
//
// Another NeteaseCloudMusicScript here:
//  [http://tieba.baidu.com/p/4651402375?pn=1]
//
// Issues || bug reports || advices are all encouraged!

var header = {
    'Referer': 'http://music.163.com/',
    'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36'
    //'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36'
};
var cookie = "appver=2.0.2";

var api = {
    "lyric": 'http://music.163.com/api/song/lyric',
    "query": "http://music.163.com/api/search/get/"
};

// Set false if do not want console output infos.
var dbg = false;

// Eng | CHN, separated by `|', but only one will be displayed in lyric search
// window (`Source' column) acording to foobar2000.exe's lang.
function get_my_name() {
    return "NeteaseCloudMusic|网易云音乐";
}

function get_version() {
    return "0.0.1";
}

function get_author() {
    return "Elia";
}

function start_search(info, callback) {

    var url;
    var title = info.Title;
    var artist = info.Artist;

    var http_client = utils.CreateHttpClient();
    var json_txt;

    // Set headers, Cookie, postData
    add_headers(header, http_client);
    http_client.addCookie("Cookie", cookie);
    http_client.addPostData(get_search_params(artist, title));

    json_txt = http_client.Request(api.query, "POST");
    if (http_client.StatusCode != 200) {
        console("Request url >>>" + api.query + "<<< error: " + http_client.StatusCode);
        return;
    }

    var obj_result = json(json_txt)["result"];
    var songs;
    if (obj_result.songs) {
        songs = obj_result.songs;
        console(songs.length);
    } else {
        console(json_txt);
        return;
    }

    console(json_txt);

    var _new_lyric = callback.CreateLyric();
    var id;

    // get lyrics
    for (var i = 0; i < songs.length; i++) {
        if (callback.IsAborting()) {
            console("User aborted!");
            break;
        }
        try {
            id = songs[i]["id"];
            artist = songs[i].artists[0].name;
            title = songs[i].name;
            album = songs[i].album.name;
        } catch (e) { };
        url = api.lyric + "?os=pc&id=" + id + "&lv=-1&kv=-1&tv=-1";
        add_headers(header, http_client);
        json_txt = http_client.Request(url);
        if (http_client.StatusCode != 200) {
            console("Request url >>>" + url + "<<< error: " + http_client.StatusCode);
            continue;
        }
        // 
        try {
            _new_lyric.LyricText = json(json_txt).lrc.lyric;
            _new_lyric.Title = title;
            _new_lyric.Artist = artist;
            _new_lyric.Album = album;
            _new_lyric.Location = url;
            _new_lyric.Source = get_my_name();
            callback.AddLyric(_new_lyric);
            (i%2 == 0) && callback.Refresh();
        } catch (e) {
            console("Unkown, failed to add lyric");
        }
    }

    _new_lyric.Dispose();

}

function add_headers(header, client) {
    for (var i in header) {
        client.addHttpHeader(i, header[i]);
    }
}

function get_search_params(artist, title, limit, type, offset) {
    if (limit == undefined) limit = 10;
    if (type == undefined) type = 1;
    if (offset == undefined) offset = 0;
    artist = process_keywords(artist);
    title = process_keywords(title);
    return "s=" + artist + "+" + title + "&limit=" + limit + "&type=" + type + "&offset=" + offset;
};


function process_keywords(str) {
    var s = str;
    s = s.toLowerCase();
    s = s.replace(/\'|·|\$|\&|–/g, "");
    //truncate all symbols
    s = s.replace(/\(.*?\)|\[.*?]|{.*?}|（.*?/g, "");
    s = s.replace(/[-/:-@[-`{-~]+/g, "");
    s = s.replace(/[\u2014\u2018\u201c\u2026\u3001\u3002\u300a\u300b\u300e\u300f\u3010\u3011\u30fb\uff01\uff08\uff09\uff0c\uff1a\uff1b\uff1f\uff5e\uffe5]+/g, "");
    return s;
}

function json(text) 
{
    try{
        var data=JSON.parse(text);
        return data;
    }catch(e){
        return false;
    }
}

function console(s) {
    if (dbg) {
        return;
    }
    fb.trace(get_my_name() + " $>  " + s);
};


// TODO: grab klyric && tlyric too.

**Comment by hong-tm** [comment]
感谢
