### ISSUE TITLE
请问怎么修改歌词字号呀

### ISSUE THREAD

**Issue by Yumin-Zhan** [cqjjjzr/MusicBee-NeteaseLyrics#14]
尤其是主面板显示歌词的时候，歌词字太小了

**Comment by cqjjjzr** [comment]
MusicBee 主面板的字号应该是和插件无关的，在“首选项”的这里改

![image](https://user-images.githubusercontent.com/6622592/148720065-eae61800-e0ce-4a4a-8152-119b1df3e541.png)

中间的“歌词”设置
