### ISSUE TITLE
Windows 安全中心报告威胁

### ISSUE THREAD

**Issue by Yumin-Zhan** [cqjjjzr/MusicBee-NeteaseLyrics#17]
下载 [NeteaseLyrics_1.8.1.zip](https://github.com/cqjjjzr/MusicBee-NeteaseLyrics/releases/download/v1.8.1/NeteaseLyrics_1.8.1.zip) 后Windows 安全中心提供的报告如下：

> **Trojan:Win32/AgentTesla!ml**
> 
> 警报级别：严重
> 状态：活动
> 类别：特洛伊木马
> 详细信息：这个程序很危险，而且执行来自攻击者的命令。
> 
> 受影响的项目：
> containerfile: D:\Downloads\NeteaseLyrics_1.8.1.zip
> file: D:\Downloads\NeteaseLyrics_1.8.1.zip->mb_NeteaseLyrics.dll

麻烦确认该 dll 文件是否存在问题

**Comment by cqjjjzr** [comment]
参照 https://getmusicbee.com/forum/index.php?topic=24313.15

系因为没有修改 AssemblyInfo.cs 中的 GUID 造成的误报，我已经在 master 分支上修复，但没有发版。如果有顾虑，可以考虑编译一份

**Comment by cqjjjzr** [comment]
已经重新更新OneDrive、Release中的文件
