### ISSUE TITLE
Feature Request: Only get translated text

### ISSUE THREAD

**Issue by fei0316** [cqjjjzr/MusicBee-NeteaseLyrics#6]
Since the default is to get original and translated text ("aaaaaaaa/bbbbbbbb"), and there is an option to get only original text ("aaaaaaaa"), I am wondering if an option can be added to get just the translated text ("bbbbbbbb"). Thanks!

**Comment by cqjjjzr** [comment]
Try this.
[NeteaseLyrics_1.5.0.zip](https://github.com/cqjjjzr/MusicBee-NeteaseLyrics/files/5352809/NeteaseLyrics_1.5.0.zip)

**Comment by fei0316** [comment]
Thank you very much! I just tested it and it is working as expected! Actually I'm still having issues where sometimes:

1. it reports as having no lyrics even though there are when I check myself,
2. it gives the wrong lyrics (and no option to show a list of candidates)

However I feel that they're due to limitations of MusicBee or Netease. I am already very happy to get Chinese lyrics this easily!

**Comment by cqjjjzr** [comment]
严格来说，我们可以实现一个比较简单的手动歌词选取，那就是利用 `Track` 的 `Custom` 字段来提供自定义的辅助选择正确歌词的信息（例如网易云的歌曲 ID）。我将在晚些时候尝试一下..

**Comment by cqjjjzr** [comment]
[NeteaseLyrics_1.5.0.zip](https://github.com/cqjjjzr/MusicBee-NeteaseLyrics/files/5361362/NeteaseLyrics_1.5.0.zip)

尝试修改曲目的 `Custom10` 字段（编辑窗口的“标签”选项卡右侧）为 `netease=123456` 的格式。曲目 ID 请参考网易云的曲目 URL（例如 `https://music.163.com/#/song?id=22826401` 中的 22826401）。

**Comment by fei0316** [comment]
抱歉，最近有點忙，忘了回覆。
感謝你的回覆，但畢竟歌詞不會怎麼更新，這樣做或許功夫比手動去網易雲複製歌詞（用瀏覽器插件）還要多？
我心目中最理想的解決方案是將搜尋結果用彈窗顯示，讓用户根據專輯、歌手選擇正確的歌詞，但MusicBee插件能不能做到就真的不清楚了。。。

**Comment by cqjjjzr** [comment]
这是能做到的. 可以直接在插件中打开一个 `Form`. 然而我并没有足够的时间完成，或许您可以提供一个 PullRequest?

**Comment by fei0316** [comment]
問題是我也不會做這個部分。既然原本的 feature request 已經解決了，我先關掉吧。
非常感謝你開發的這個插件！
