### ISSUE TITLE
两年没更新，好像不怎么行了啊

### ISSUE THREAD

**Issue by TaivasJumala** [cqjjjzr/MusicBee-NeteaseLyrics#7]

**Comment by cqjjjzr** [comment]
不能获取了吗

upd: 测试目前仍然能获取.

**Comment by TaivasJumala** [comment]
额，我改字体把 musicbee 搞崩了，我再试试

**Comment by BurgessX** [comment]
为什么只能在 正在播放 的左侧显示歌手的介绍信息，并没有歌词？

**Comment by cqjjjzr** [comment]
![image](https://user-images.githubusercontent.com/6622592/131534948-64f442f3-8631-4b0c-8748-f0b23a6530a5.png)

@BurgessX ：在如图所示位置右键选择歌词
另外你应当开一个新的Issue而不是复用当前Issue

**Comment by Taivasjumala** [comment]
2021/9/25

**Comment by Taivasjumala** [comment]
2021/9/25
经过重新测试，此问题可能由两个原因：
1. 挂了梯子，查询歌词变成从 chartlyrics.com 查询

**Comment by TaivasJumala** [comment]
2021/9/25
MusicBee 3.4.7805
Released on May 17, 2021
插件版本 1.40
Windows 10

经过重新测试，此问题可能由两个原因导致：

1.挂了梯子，查询歌词会变成从 chartlyrics.com (第二优先级，歌词没有时间戳) 查询，而非设置为第一优先级的 Netease
2.从 Microsoft Store 获取的 Muscibee
（此前因为想要拥有 Microsoft Store 支持的自动更新 Muscibee 的功能而从此渠道下载的 Musicbee，这会导致因为权限不足无法在文件夹写入文件而无法更换 Musicbee 图标，可能是因为 Microsoft Store 上安装的应用需要符合一定安全策略）

不能确定具体以上哪个问题导致，在使用从官网下载的 Installer 安装后，关闭 V2RayN 代理后能正常获取歌词，屏幕歌词能也能自动滚动。

**Comment by cqjjjzr** [comment]
@Taivasjumala   
1. 挂梯子后网易的 API 可能屏蔽了海外 IP，所以 `Netease` 查询会失败
2. MS Store 上的 app 经常有权限问题，与插件相关的 app 不太推荐在 MS Store 下载
