### ISSUE TITLE
获取不到歌词了，是不是网易把接口换了

### ISSUE THREAD

**Issue by 0x915** [cqjjjzr/MusicBee-NeteaseLyrics#8]
。。

**Comment by cqjjjzr** [comment]
貌似确实出来了问题，我晚些时候看看

**Comment by 0x915** [comment]
> 貌似确实出来了问题，我晚些时候看看

大佬的回复简直神速。。。

**Comment by cqjjjzr** [comment]
closed in https://github.com/cqjjjzr/MusicBee-NeteaseLyrics/releases/tag/v1.6.0
