### ISSUE TITLE
No longer working internationally

### ISSUE THREAD

**Issue by Normz-BIT** [cqjjjzr/MusicBee-NeteaseLyrics#9]
The new query only returns {
	"result": "A very long String",
	"code": 200,
	"abroad": true
}
and not the lyrics

**Comment by cqjjjzr** [comment]
My query works well.

the "`abroad: true`" may indicate that you're making the request using an IP outside China and failed to retrieve the lyrics due to copyright issues. Try using a proxy or something?

**Comment by DjFuryX** [comment]
no luck still doesn't work after trying several different proxies

**Comment by Normz-BIT** [comment]
I can't find a VPN that gives me a Chinese IP. Is SSH blocked in china?

**Comment by cqjjjzr** [comment]
It's not blocked, it's just basically because of the lack of need for a VPN with a Chinese IP, so I have no clue about this.

Could you try running these two queries?  

http://music.163.com/api/search/get/web?csrf_token=hlpretag=&hlposttag=&s=%E3%82%AB%E3%82%BF%E3%82%AA%E3%83%A2%E3%82%A4&type=1&offset=0&total=true&limit=6

https://music.163.com/api/song/lyric?os=pc&id=431259256&lv=-1&kv=-1&tv=-1

**Comment by Normz-BIT** [comment]
The second one works.

**Comment by Normz-BIT** [comment]
![Screenshot (52)](https://user-images.githubusercontent.com/89606721/147519530-aae1b48c-a18e-4af0-a605-325bc1ff029b.png)

**Comment by cqjjjzr** [comment]
Then I would recommend you to use the "Custom10" approach described in the README. Find the song id in the Netease Music webpage and set it in the music metadata.

**Comment by Normz-BIT** [comment]
Same as before
![music123](https://user-images.githubusercontent.com/89606721/147530704-97a7e438-ab8f-45e6-ac95-bdfc245726b4.PNG)

**Comment by cqjjjzr** [comment]
You shouldn't use this API endpoint. Instead, go to https://music.163.com/#/search and search your music, find the ID, and follow the instructions in the README.md to attach it to your local song..

**Comment by Normz-BIT** [comment]
That's what I did
![music122](https://user-images.githubusercontent.com/89606721/147531275-ec54af8a-4230-4edd-a3c8-aa84957d923b.PNG)

**Comment by cqjjjzr** [comment]
It should be `netease=1902119150`

the "123123" is an example... and the text in the bracket is the description

**Comment by Normz-BIT** [comment]
Like this?
![music12](https://user-images.githubusercontent.com/89606721/147532004-b17b4ecd-4243-48ad-9c7d-e9e1893cfd4d.PNG)
Still doesn't work though

**Comment by cqjjjzr** [comment]
![image](https://user-images.githubusercontent.com/6622592/147532182-736208c6-c2c3-42a3-adf3-bf3af0222ec1.png)

the bracket along with text in it should be REMOVED

**Comment by Normz-BIT** [comment]
You should really update that README.md my guy and yeah it works now but this really defeats the purpose of having it automated,

**Comment by cqjjjzr** [comment]
Well, that's because the API endpoint isn't working outside China :(

Maybe I need to seek another one

**Comment by Normz-BIT** [comment]
Seems like the problem is the web in the request
![Screenshot (55)](https://user-images.githubusercontent.com/89606721/147535377-0ab8b884-b04b-4bb0-8683-da76693379f9.png)
removing it results in this
![Screenshot (56)](https://user-images.githubusercontent.com/89606721/147535462-293fd8da-4c19-4994-9659-ae2218fb665c.png)

**Comment by cqjjjzr** [comment]
Oh? this seems promising.

I'll soon give it a try, thanks :)

**Comment by Normz-BIT** [comment]
No problem.

**Comment by cqjjjzr** [comment]
[NeteaseLyrics_Test.zip](https://github.com/cqjjjzr/MusicBee-NeteaseLyrics/files/7788432/NeteaseLyrics_Test.zip)

Could try this out? If it works, I'll release a new version.

**Comment by Normz-BIT** [comment]
Yes thank you it's working now.

**Comment by Normz-BIT** [comment]
Only problem is if there are multiple results it doesn't chose any.
